import { config, FIRESTORE_DOCUMENT_EVENTS } from "@intmax2-function/shared";

// batch
export const MAX_RELAYER_BATCH_SIZE = 450;

// db
export const relayerDBName = config.MOCK_L1_SENDER_EVENT_DECODE_ENABLED
  ? FIRESTORE_DOCUMENT_EVENTS.MOCK_MESSENGER_RELAYER
  : FIRESTORE_DOCUMENT_EVENTS.MOCK_MESSENGER_RELAYER_UNDECODED;
